# -*- coding: utf-8 -*-
{
    'name': 'interior project',
    'version': '17.0.3.0.3',
    'category': '',
    'summary': "",
    'author': 'quantumbot',
    'company': 'quantumbot',
    'maintainer': 'quantumbot',
    'website': "https://quantumbot.in/",
    'depends': ['web', 'base', 'mail', 'base_import', 'website'],
    'data': [
        'security/security_template.xml',
        'security/ir.model.access.csv',
        'views/interior_projects_view.xml',
        'views/payment_method_view.xml',
        'views/vendor_payment_method_view.xml',
        'views/res_customer_view.xml',
        'views/res_agency_view.xml',
        'views/menuitem_hide.xml',
        'views/expenses_category_view.xml',
        'views/agency_category_view.xml',
        'views/project_expense_view.xml',
        'views/weblogin_template.xml',
        'wizard/project_report_view.xml',
        'wizard/project_report_menu_view.xml',
        'wizard/project_report_template.xml',
        'wizard/work_category_template.xml',
        'wizard/work_category_view.xml',
        'wizard/agency_report_template.xml',
        'wizard/agency_report_view.xml',
        'wizard/agency_report_template_new.xml',

    ],
    'assets': {
        'web.assets_backend': [
            # 'saara_spaces_models/static/src/**/*.xml',
            "https://cdn.jsdelivr.net/npm/chart.js",
            'saara_spaces_models/static/src/view/custom_dashboard.xml',
            'saara_spaces_models/static/src/view/reports_custom.xml',
            'saara_spaces_models/static/src/js/reports_screen.js',
            'saara_spaces_models/static/src/js/custome_dashboard.js',
        ],
    },

    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
    'sequence': 2,
}
